### ISSUE TITLE
最早创建的emqx pod所在节点挂掉会导致emqx集群服务中断

### ISSUE THREAD

**Issue by zchcc** [emqx/emqx-operator#1025]
**Describe the bug**
最早创建的emqx pod所在节点挂掉会导致emqx集群服务中断，中断会持续到pod被k8s置为terminating后恢复，常见持续时间可能是5分钟。其他节点挂掉不会导致集群服务中断。

**To Reproduce**
1. 正常用emqx-operator部署一个3节点的emqx集群
2. 找到最早创建的emqx pod所在的服务器节点，然后poweroff该linux服务器
3. 观察 emqx-dashboard的 endpoint，可以看到持续一段时间的无ep状态。
  
![image](https://github.com/emqx/emqx-operator/assets/2937437/5e3930c4-5ad2-4d51-84e0-65f8fd09df1a)

**Expected behavior**
无论poweroff哪个节点，emqx集群服务都不应该中断

**Anything else we need to know?**:
我看emqx-operator目前的逻辑是找到最早创建的pod作为API服务端，请求集群节点信息，假如这个pod挂了，那么就会导致coreNodes被赋空，然后所有pod的`apps.emqx.io/on-serving`被赋成false，服务就中断了。
`controllers/apps/v2beta1/update_emqx_status.go:83`这里即便返回了err，下面依旧把空的coreNodes赋过去了
![image](https://github.com/emqx/emqx-operator/assets/2937437/e26632ea-6681-4726-b351-2c270558b964)

**Environment details:**:
- Kubernetes version: 1.26.15
- Cloud-provider/provisioner: none
- emqx-operator version: 2.2.18
- Install method: static manifests

**Comment by Rory-Z** [comment]
EMQX core node is deploy by Kubernetes steatefulSet, and when the Kubernetes node be power off, statefulSet do not provide any guarantees on the termination, so that is reason.
For EMQX cluster, the EMQX core node is stateful node, it should not be closed, if it's closed, will need operation and maintenance personnel be involved.
EMQX replicant node is the stateless node, it can be close, so maybe you can deploy EMQX core node to some strong Kubernetes node, and EMQX core node just manager all of EMQX cluster, deploy EMQX replicant node to other Kubernetes node, and EMQX replicant node can be accept all of MQTT connection.
