### ISSUE TITLE
How to update EMQX resource when using bootstrapConfig

### ISSUE THREAD

**Issue by Rory-Z** [emqx/emqx-operator#480]
### Discussed in https://github.com/emqx/emqx-operator/discussions/471

<div type='discussions-op-text'>

<sup>Originally posted by **mariusstaicu** November 21, 2022</sup>
When using bootstrapConfig one cannot reapply the yaml and update other portions of it because of the validation error:
```
admission webhook "validator.apps.emqx.io" denied the request: bootstrap config cannot be updated, old bootstrap config: 
```

How to update the EQMX resource without this validation failure? </div>

**Comment by rubengees** [comment]
I still have this problem with `emqx-operator` 2.1.0 and `emqx` 5.0.16 when using `kubectl apply -f`. The error is:

```
bootstrap config cannot be updated, old bootstrap config: node {
  cookie = emqxsecretcookie
  data_dir = "data"
  etc_dir = "etc"
}
cluster {
  discovery_strategy = dns
  dns {
    record_type = srv
    name = "name"
  }
}
listeners.tcp.default {
  bind = "0.0.0.0:1883"
  max_connections = 1024000
}
sysmon.vm.long_schedule = disabled
, new bootstrap config: {node:{data_dir:data, etc_dir:etc, cookie:emqxsecretcookie}, cluster:{discovery_strategy:dns, dns:{record_type:srv, name:"name"}}, dashboard:{listeners:{http:{bind:18083}}, default_username:admin, default_password:public}, listeners:{tcp:{default:{bind:"0.0.0.0:1883", max_connections:1024000}}}}
```

The `bootstrapConfig` in my template looks like this, so where does the new bootstrap config come from?

```yaml
apiVersion: apps.emqx.io/v2alpha1
kind: EMQX
metadata:
  name: emqx
  namespace: some-ns
spec:
  image: emqx/emqx:5.0.16
  bootstrapConfig: |
    node {
      cookie = emqxsecretcookie
      data_dir = "data"
      etc_dir = "etc"
    }
    cluster {
      discovery_strategy = dns
      dns {
        record_type = srv
        name = "name"
      }
    }
    listeners.tcp.default {
      bind = "0.0.0.0:1883"
      max_connections = 1024000
    }
```

Is there a way to ignore the `bootstrapConfig` so I can deploy again?

**Comment by rubengees** [comment]
I thin this happens because of the object merging here: https://github.com/emqx/emqx-operator/blob/3c955c372cf5eeec9a450a3387356a31693edec1/apis/apps/v2alpha1/emqx_webhook.go#L201

The default config has this block: https://github.com/emqx/emqx-operator/blob/3c955c372cf5eeec9a450a3387356a31693edec1/apis/apps/v2alpha1/emqx_webhook.go#L188-L194

My existing `bootstrapConfig` does not have that block so validation will never be successful. How can I delete the existing `bootstrapConfig` to make this work?

**Comment by Rory-Z** [comment]
Hi, @rubengees Sorry for delay
Did you change the bootstrap config in the two kubectl apply runs?

In https://github.com/emqx/emqx-operator/blob/3c955c372cf5eeec9a450a3387356a31693edec1/apis/apps/v2alpha1/emqx_webhook.go#L201
This is to merge the user's bootstrap config with the default bootstrap config, they will eventually be parsed into a string output of https://github.com/emqx/emqx-operator/blob/3c955c372cf5eeec9a450a3387356a31693edec1/apis/apps/v2alpha1/emqx_webhook.go#L202

**Comment by rubengees** [comment]
I don't know how exactly the old config without the new block was created. It might be from an older version of the operator when the cluster was initially created.

The main problem is that when I have an incorrect config, there seems to be no way to fix it since the validating webhook denies all deployments.

In the example above I deleted the operator and the webhooks and then `kubectl apply`. That works, because the webhooks do not exist. When I deploy the same file again, the deployment fails with the above error.

**Comment by Rory-Z** [comment]
> The main problem is that when I have an incorrect config, there seems to be no way to fix it since the validating webhook denies all deployments.

Bootstrap is designed not to be updated, if you fill in the format incorrectly the webhook will block it and report an error, if EMQX is already running then you can change the EMQX configuration via the Dashboard.

**Comment by Rory-Z** [comment]
> 



> Yes, I understand and that's fine. But once I have an incorrect config I can never deploy again and thus never update the EMQX version or change other things that _are_ designed to be updated, because the webhook does not accept other changes due to the bootstrap config being incorrect. I think this is similar to #554.

Yes, it is a problem. 
The reason we disable bootstrap config updates is the following: 
The bootstrap config is mounted to `/opt/emqx/etc/emqx.conf` in the EMQX container, and in EMQX, the configuration modified via dashboard is stored in `data/cluster-overwrite.conf`, and `data/ cluster-overwrite.conf` has a higher priority than `etc/emqx.conf`, this can be confusing if the user modifies the configuration file via both Dashboard and `etc/emqx.conf` so we disable updating the bootstrap config.

If you have any good ideas, please let me know

**Comment by clive-jevons** [comment]
@Rory-Z one idea could be to have a separate CRD for the config based on the REST API spec of the broker / cluster itself. Then the operator could reconcile the broker's config via the REST API rather than via files?

E.g.: in the reconcile loop (if a config CR was provided) it could check the current "global zone" config using https://www.emqx.io/docs/en/v5.0/admin/api-docs.html#tag/Configs/paths/~1configs~1global_zone/get ... and if the values don't match between the CR and the broker, then use https://www.emqx.io/docs/en/v5.0/admin/api-docs.html#tag/Configs/paths/~1configs~1global_zone/put to update them so that they match

This way, in a true DevOps / GitOps manner, you could have your config represented as a CR yaml in your git repo, and config updates will be rolled out the usual way (via CI pipelines or something like ArgoCD).
Also, by constantly reconciling, the operator can ensure that the live state of the cluster's config matches the expectations expressed via the resource - preventing haphazard "ClickOps" style shenanigans 😂

WDYT?

**Comment by Rory-Z** [comment]
Hi, @clive-jevons Good idea. In fact, we have already done this. You can check out this PR: https://github.com/emqx/emqx-operator/pull/849/files#diff-9ec5fbbb1e0c679351d450279506f193c3d005681450eb90ff1c86592e9c2cc8

But we didn't use new single CRD to manager EMQX's config, we also use EMQX CR's filed, do you have any suggestions?

You can try this via EMQX Operator 2.2.0-alpha.1, but the alpha version means that there may still be changes, so it is not recommended to use it in a production environment.

**Comment by clive-jevons** [comment]
@Rory-Z Noice!! Looks like pretty much exactly what I'd been hoping for 😁👍 Thnx 🙏🏻
